import { Room } from '@/types';

export const rooms: Room[] = [
  {
    id: 'corner-east',
    name: '東側角部屋',
    nameEn: 'East Corner Room',
    nameZh: '东侧角房',
    type: 'corner',
    price: 12000,
    maxGuests: 2,
    size: 25,
    amenities: ['エアコン', 'WiFi', '冷蔵庫', '電子レンジ', 'バスタオル'],
    images: ['/images/corner-east-1.jpg', '/images/corner-east-2.jpg'],
    description: '朝日が美しく差し込む東側の角部屋です。静かで快適な滞在をお楽しみいただけます。',
    descriptionEn: 'East corner room with beautiful morning sunlight. Enjoy a quiet and comfortable stay.',
    descriptionZh: '朝阳美丽的东侧角房。享受安静舒适的住宿体验。',
  },
  {
    id: 'standard-1',
    name: 'スタンダードルーム（1号室）',
    nameEn: 'Standard Room (Room 1)',
    nameZh: '标准间（1号房）',
    type: 'standard',
    price: 10000,
    maxGuests: 2,
    size: 20,
    amenities: ['エアコン', 'WiFi', '冷蔵庫', 'バスタオル'],
    images: ['/images/standard-1-1.jpg', '/images/standard-1-2.jpg'],
    description: '快適で機能的なスタンダードルームです。必要な設備が揃っています。',
    descriptionEn: 'Comfortable and functional standard room with all necessary amenities.',
    descriptionZh: '舒适实用的标准间，配备所有必需设施。',
  },
  {
    id: 'connecting-1',
    name: '中央連結部屋（A）',
    nameEn: 'Central Connecting Room (A)',
    nameZh: '中央连通房（A）',
    type: 'connecting',
    price: 11000,
    maxGuests: 3,
    size: 22,
    amenities: ['エアコン', 'WiFi', '冷蔵庫', 'バスタオル', '連結ドア'],
    images: ['/images/connecting-1-1.jpg', '/images/connecting-1-2.jpg'],
    description: '隣の部屋と繋がることができる特別な部屋です。グループ旅行に最適。',
    descriptionEn: 'Special room that can connect to the adjacent room. Perfect for group travel.',
    descriptionZh: '可与邻房相连的特殊房间，非常适合团体旅行。',
    isConnecting: true,
    connectsTo: 'connecting-2',
  },
  {
    id: 'connecting-2',
    name: '中央連結部屋（B）',
    nameEn: 'Central Connecting Room (B)',
    nameZh: '中央连通房（B）',
    type: 'connecting',
    price: 11000,
    maxGuests: 3,
    size: 22,
    amenities: ['エアコン', 'WiFi', '冷蔵庫', 'バスタオル', '連結ドア'],
    images: ['/images/connecting-2-1.jpg', '/images/connecting-2-2.jpg'],
    description: '隣の部屋と繋がることができる特別な部屋です。グループ旅行に最適。',
    descriptionEn: 'Special room that can connect to the adjacent room. Perfect for group travel.',
    descriptionZh: '可与邻房相连的特殊房间，非常适合团体旅行。',
    isConnecting: true,
    connectsTo: 'connecting-1',
  },
  {
    id: 'standard-2',
    name: 'スタンダードルーム（2号室）',
    nameEn: 'Standard Room (Room 2)',
    nameZh: '标准间（2号房）',
    type: 'standard',
    price: 10000,
    maxGuests: 2,
    size: 20,
    amenities: ['エアコン', 'WiFi', '冷蔵庫', 'バスタオル'],
    images: ['/images/standard-2-1.jpg', '/images/standard-2-2.jpg'],
    description: '快適で機能的なスタンダードルームです。必要な設備が揃っています。',
    descriptionEn: 'Comfortable and functional standard room with all necessary amenities.',
    descriptionZh: '舒适实用的标准间，配备所有必需设施。',
  },
  {
    id: 'corner-west',
    name: '西側角部屋',
    nameEn: 'West Corner Room',
    nameZh: '西侧角房',
    type: 'corner',
    price: 12000,
    maxGuests: 2,
    size: 25,
    amenities: ['エアコン', 'WiFi', '冷蔵庫', '電子レンジ', 'バスタオル'],
    images: ['/images/corner-west-1.jpg', '/images/corner-west-2.jpg'],
    description: '夕日が美しく見える西側の角部屋です。ロマンチックな滞在をお楽しみください。',
    descriptionEn: 'West corner room with beautiful sunset views. Enjoy a romantic stay.',
    descriptionZh: '可欣赏美丽夕阳的西侧角房。享受浪漫的住宿体验。',
  },
];